In [1]:
import numpy as np
import time 

In [150]:
A = np.array([[12, -51, 4],
              [6, 167, -68],
              [-4, 24, -41]])

print(np.linalg.matrix_rank(A))
np.linalg.qr(A, mode='complete')

3


(array([[-0.85714286,  0.39428571,  0.33142857],
        [-0.42857143, -0.90285714, -0.03428571],
        [ 0.28571429, -0.17142857,  0.94285714]]),
 array([[ -14.,  -21.,   14.],
        [   0., -175.,   70.],
        [   0.,    0.,  -35.]]))

In [161]:
7*Q, R

(array([[ 6.  , -2.76, -2.32],
        [ 3.  ,  6.32,  0.24],
        [-2.  ,  1.2 , -6.6 ]]),
 array([[ 14.,  21., -14.],
        [  0., 175., -70.],
        [  0.,   0.,  35.]]))

In [51]:
#a_1 is the first column of A
r_11 = np.linalg.norm(A[:, 0], ord = 2)
q_1 = (1/r_11) * A[:, 0]

r_12 = np.dot(q_1, A[:, 1])
r_22 = np.linalg.norm(A[:, 1] - r_12 * q_1, ord = 2)
q_2 = (1/r_22)*(A[:, 1] - r_12 * q_1)

print(r_12, r_22, q_2)

9.601136296387953 0.9045340337332909 [ 0.90453403  0.30151134 -0.30151134]


In [151]:
m, n = A.shape
Q = np.zeros((m, m))
R = np.zeros((m, n))


for i in range(m): #Row Iter
    prev = 0 # used to catch r_{jk}q_j in sum
    
    if i == 0:
        #first iter has no previous -> does not depend on previous

        R[i, i] = np.linalg.norm(A[:, i], ord = 2)
        assert R[i, i] != 0, "Diagonal is zero, function cannot continue"
        Q[:, i] = (1/R[i, i]) * A[:, i]
        continue

    if i == 1:
        #Does something different as well...
        R[0, i] = np.dot(Q[:, 0], A[:, i])
        R[i, i] = np.linalg.norm(A[:, i] - R[0, i] * Q[:, 0], ord = 2)
        assert R[i, i] != 0, "Diagonal is zero, function cannot continue"
        Q[:, i] = (1/R[i, i]) * (A[:, i] - R[0, i] * Q[:, 0])
        continue
    
    
    for j in range(0, i+1): # maintain upper triangularity
        
        if i != j:
            R[j, i] = np.dot(Q[:, j], A[:, i])
            print(f'R[{j, i}]: {R[j, i]}')
            prev += R[j, i] * Q[:, j]
            
            
        else: #Diagonal term, take prev
            print(f'Coords: {(i, j)}')
            print("prev: {}".format(prev))
            R[i, i] = np.linalg.norm(A[:, i] - prev, ord = 2)
            assert R[i, i] != 0, "Diagonal is zero, function cannot continue"
            Q[:, j] = (1/R[i, i]) * (A[:, i] - prev)

R[(0, 2)]: -14.000000000000002
R[(1, 2)]: -70.0
Coords: (2, 2)
prev: [ 15.6 -69.2  -8. ]


In [163]:
type(A)

numpy.ndarray

In [238]:
def my_qr(A: np.ndarray):
    """
    Vectorizes an unvectorized Gram Schmidt QR decomposition.
    """
    
    def unvect_qr(A: np.ndarray):
        """
        Returns the QR factorization of a nonsingular array
        via (classical) Gram-Schmidt.

        Parameters
        ----------
        A: np.ndarray
            The matrix with which we find the QR factorization.
            Must be nonsingular, sized n x n

        Returns
        -------
        Q: np.ndarray
            A set of orthonormal column vectors of size n x n

        R: np.ndarray
            An upper triangular matrix
        """
        print(A)
        m, n = A.shape
        Q = np.zeros((m, m))
        R = np.zeros((m, n))


        for i in range(0, m): #Row Iter
            prev = 0 # used to catch r_{jk}q_j in sum
            for j in range(0, i+1): # maintain upper triangularity
                if i != j:
                    R[j, i] = np.dot(Q[:, j], A[:, i])
                    prev += R[j, i] * Q[:, j]
                else: #Diagonal term, take prev
                    R[i, i] = np.linalg.norm(A[:, i] - prev, ord = 2)
                    assert R[i, i] != 0, "Diagonal is zero, function cannot continue"
                    Q[:, j] = (1/R[i, i]) * (A[:, i] - prev)
    
        return (Q, R)
        
    res = np.vectorize(unvect_qr, otypes=[int])
    return res(A)

In [239]:
A = np.array([[12, -51, 4],
              [6, 167, -68],
              [-4, 24, -41]])
my_qr(A)

12


AttributeError: 'int' object has no attribute 'shape'

In [245]:
def my_qr(A: np.ndarray):
        """
        Returns the QR factorization of a nonsingular array
        via (classical) Gram-Schmidt.

        Parameters
        ----------
        A: np.ndarray
            The matrix with which we find the QR factorization.
            Must be nonsingular, sized n x n

        Returns
        -------
        Q: np.ndarray
            A set of orthonormal column vectors of size n x n

        R: np.ndarray
            An upper triangular matrix
        """
        m, n = A.shape
        Q = np.zeros((m, m))
        R = np.zeros((m, n))

        for i in range(0, m): #Row Iter
            prev = 0 # used to catch r_{jk}q_j in sum
            for j in range(0, i+1): # maintain upper triangularity
                if i != j:
                    R[j, i] = np.dot(Q[:, j], A[:, i])
                    prev += R[j, i] * Q[:, j]
                else: #Diagonal term, take prev
                    R[i, i] = np.linalg.norm(A[:, i] - prev, ord = 2)
                    assert R[i, i] != 0, "Diagonal is zero, function cannot continue"
                    Q[:, j] = (1/R[i, i]) * (A[:, i] - prev)
    
        return (Q, R)
    
A = np.array([[1,2,3],
              [4,5,6],
              [7,12,9]])
res = my_qr(A)

In [246]:
np.matmul(res[0].T, res[0])

array([[ 1.00000000e+00,  2.63083884e-16,  1.84985352e-15],
       [ 2.63083884e-16,  1.00000000e+00, -1.73384971e-15],
       [ 1.84985352e-15, -1.73384971e-15,  1.00000000e+00]])